### PR TITLE
Deepali

### PR DESCRIPTION
**Pull request by deepalisingh11**

### CODE REVIEW

**Comment by vsvipul** [comment]
@deepalisingh11 Make changes to your already existing entry. DOn't create a new one.

**Comment by vsvipul** [comment]
Good work!

**Comment by deepalisingh11** [comment]
@vsvipul i asked you if we can edit. you told it's only possible with a new branch. 

but i tried doing everything on my own from the start this time. and i also tried resolving conflicts. so it was good practice.

**Comment by vsvipul** [comment]
Yes it is possible with the same branch as well. But not on the same PR. You asked if it was possible on the same PR or not. After a PR Is merged, you can't do anything to that PR.

**Comment by vsvipul** [comment]
GOod ! Keep going this way and use git everyday.. TBi smjh aega ho kya rha hai .

**Comment by deepalisingh11** [comment]
> Yes it is possible with the same branch as well. But not on the same PR. You asked if it was possible on the same PR or not. After a PR Is merged, you can't do anything to that PR.

oh alright. yeah that's what i meant, if it can be edited after it is mergered. it couldn't, so i just created a new branch.

**Comment by deepalisingh11** [comment]
> GOod ! Keep going this way and use git everyday.. TBi smjh aega ho kya rha hai .

okay :)

**Pull request merged**
